leftnav:
- identifier: 63beabe5-d756-6e9e-8558-700a2cf378f6
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 97ff4825-8dc4-7fbe-9de9-b00714d004ec
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: 289d5967-ddf1-e3d5-3c94-224464db3019
  name: Readings
  url: /pages/readings
  weight: 30
- identifier: 44b2b094-d95f-4afe-cfd6-f071489a85a9
  name: Assignments
  url: /pages/assignments
  weight: 40
